library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wno-name-shadowing
    - -fwarn-monomorphism-restriction
    - -Werror

dependencies:
  - base >= 4.7 && < 5
  - rio
  - rel8
  - aeson
  - bytestring
  - containers
  - http-media
  - lucid
  - mtl
  - servant
  - servant-rawm
  - servant-rawm-server
  - servant-server
  - stm
  - text
  - time
  - transformers
  - warp

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - TypeApplications

name: todomvc

executables:
  todomvc:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -flate-specialise
      - -fspecialise-aggressively
    dependencies:
      - todomvc
